name: ClusterFuzzLite Batch Fuzzing

on:
  schedule:
    - cron: "41 6 * * 0"
  workflow_dispatch:

permissions: read-all

jobs:
  batch:
    name: Batch Fuzzing (${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - uses: actions/checkout@v6
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: batch
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
          parallel-fuzzing: true
